### Fake News Classifier

In [53]:
import pandas as pd
data_train = pd.read_csv('/Users/felipe_q/Desktop/NLP_Kaggle_FakeNews/train.csv')

In [54]:
data_train.head(10)

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
5,5,Jackie Mason: Hollywood Would Love Trump if He...,Daniel Nussbaum,"In these trying times, Jackie Mason is the Voi...",0
6,6,Life: Life Of Luxury: Elton John’s 6 Favorite ...,NaN,Ever wonder how Britain’s most iconic pop pian...,1
7,7,Benoît Hamon Wins French Socialist Party’s Pre...,Alissa J. Rubin,"PARIS — France chose an idealistic, traditi...",0
8,8,Excerpts From a Draft Script for Donald Trump’...,NaN,Donald J. Trump is scheduled to make a highly ...,0
9,9,"A Back-Channel Plan for Ukraine and Russia, Co...",Megan Twohey and Scott Shane,A week before Michael T. Flynn resigned as nat...,0

### Cleaning the Data

In [55]:
data_train.isna().sum()/len(data_train) *100

id        0.000000
title     2.682692
author    9.408654
text      0.187500
label     0.000000
dtype: float64

In [56]:
print(data_train.shape)

(20800, 5)

In [57]:
data_train.dropna(inplace = True)
data_train.isna().sum()/len(data_train)

id        0.0
title     0.0
author    0.0
text      0.0
label     0.0
dtype: float64

In [58]:
data_train.reset_index(drop = True, inplace = True)

In [59]:
print(data_train.shape)

(18285, 5)

#### Removing StopWords

In [60]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [67]:
import re
from unidecode import unidecode
import spacy
nlp = spacy.load('en_core_web_sm')

#bad_chars  = [',','']
def preprocessing_text(paragraph):
    
    para_clean = unidecode(paragraph)
    lower_case = para_clean.lower()
    no_numbers = re.sub(r'\d', '', lower_case) #Remove Numbers out of the Text
    no_special_chars = re.sub(r'[^ a-zA-Z]', '', no_numbers) #Remove Special Characters
    #out of the text
    
    return no_special_chars

def stopwords_lemma(paragraph):
    
    empty_par = []
    words_mod_lemma = nltk.tokenize.word_tokenize(paragraph)
    
    #Is taking too much time
    #doc = nlp(paragraph)    
    #words_mod_lemma = [word.lemma_ for word in doc if word not in set(stop_words)]
    words_mod_lemma_2 = [word for word in words_mod_lemma if word not in stop_words]
    
    paragraph_2 = ' '.join(words_mod_lemma_2)
    
    return paragraph_2

In [68]:
data_train.title = data_train.title.apply(preprocessing_text)
data_train.text = data_train.text.apply(preprocessing_text)

data_train.title = data_train.title.apply(stopwords_lemma)
data_train.text = data_train.text.apply(stopwords_lemma)

In [69]:
data_train

,id,title,author,text,label
0,0,house dem aide didnt even see comeys letter ja...,Darrell Lucus,house dem aide didnt even see comeys letter ja...,1
1,1,flynn hillary clinton big woman campus breitbart,Daniel J. Flynn,ever get feeling life circles roundabout rathe...,0
2,2,truth might get fired,Consortiumnews.com,truth might get fired october tension intellig...,1
3,3,civilians killed single us airstrike identified,Jessica Purkiss,videos civilians killed single us airstrike id...,1
4,4,iranian woman jailed fictional unpublished sto...,Howard Portnoy,print iranian woman sentenced six years prison...,1
...,...,...,...,...,...
18280,20795,rapper ti trump poster child white supremacy,Jerome Hudson,rapper unloaded black celebrities met donald t...,0
18281,20796,nfl playoffs schedule matchups odds new york t...,Benjamin Hoffman,green bay packers lost washington redskins wee...,0
18282,20797,macys said receive takeover approach hudsons b...,Michael J. de la Merced and Rachel Abrams,macys today grew union several great names ame...,0
18283,20798,nato russia hold parallel exercises balkans,Alex Ansary,nato russia hold parallel exercises balkans pr...,1
18284,20799,keeps f alive,David Swanson,david swanson author activist journalist radio...,1

### Generate the model analysis

Remember that count vectorizer is called bag of words

In [74]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [93]:
cv = CountVectorizer(max_features = 5000, ngram_range= (1,3))
X = cv.fit_transform(data_train.title).toarray()

In [102]:
title_count = pd.DataFrame(X, columns = cv.get_feature_names())

In [114]:
title_count

,abandoned,abc,abc news,abe,abedin,abedins,able,abortion,abroad,absolutely,...,youve,zealand,zero,zika,zika virus,zionist,zone,zones,zu,zuckerberg
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18280,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18281,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18282,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18283,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18284,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Generating Train Test Split Data

In [115]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, data_train['label'], test_size = 0.3, random_state = 42)

### Multinomial NB Algorithm

In [116]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

In [118]:
from sklearn import metrics

In [119]:
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)

In [121]:
print(metrics.classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      3107
           1       0.86      0.89      0.87      2379

    accuracy                           0.89      5486
   macro avg       0.89      0.89      0.89      5486
weighted avg       0.89      0.89      0.89      5486

In [122]:
print(metrics.confusion_matrix(y_test, pred))

[[2758  349]
 [ 261 2118]]

In [127]:
feature_names = cv.get_feature_names()

In [123]:
classifier.coef_[0]

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)

array([-9.94087967, -8.55458531, -9.02458894, ..., -9.53541456,
       -8.6881167 , -9.24773249])

In [130]:
#This are the words that doesn´t make post to be fake
sorted(zip(classifier.coef_[0], feature_names), reverse = True)[:20]

[(-4.05200171342031, 'trump'),
 (-4.325928410803606, 'hillary'),
 (-4.447818228412642, 'clinton'),
 (-4.97106637217719, 'us'),
 (-5.024555057128176, 'election'),
 (-5.11256593445089, 'new'),
 (-5.153387928971145, 'comment'),
 (-5.254129498772676, 'video'),
 (-5.33072194425406, 'war'),
 (-5.3765314802853545, 'fbi'),
 (-5.424540699471715, 'hillary clinton'),
 (-5.552622487328673, 'world'),
 (-5.630080546367677, 'donald'),
 (-5.736187052362225, 'obama'),
 (-5.781996588393519, 'donald trump'),
 (-5.838236306716395, 'emails'),
 (-5.863342227847471, 'russia'),
 (-5.89782840391864, 'trumps'),
 (-5.924496651000802, 'wikileaks'),
 (-6.028856666325044, 'vote')]

In [132]:
#This are the words that make a post to be fake
sorted(zip(classifier.coef_[0], feature_names))[:20]

[(-10.634026852313136, 'abroad'),
 (-10.634026852313136, 'act new'),
 (-10.634026852313136, 'act new york'),
 (-10.634026852313136, 'actions'),
 (-10.634026852313136, 'advice'),
 (-10.634026852313136, 'agenda breitbart'),
 (-10.634026852313136, 'aleppo new'),
 (-10.634026852313136, 'aleppo new york'),
 (-10.634026852313136, 'ali'),
 (-10.634026852313136, 'amazon'),
 (-10.634026852313136, 'america breitbart'),
 (-10.634026852313136, 'america new york'),
 (-10.634026852313136, 'amp'),
 (-10.634026852313136, 'amy'),
 (-10.634026852313136, 'amy schumer'),
 (-10.634026852313136, 'angel'),
 (-10.634026852313136, 'angela'),
 (-10.634026852313136, 'angela merkel'),
 (-10.634026852313136, 'angeles'),
 (-10.634026852313136, 'appearance')]

### Now we try model but with TFIDF and with the text column

In [134]:
data_train.loc[0,'text']

'house dem aide didnt even see comeys letter jason chaffetz tweeted darrell lucus october subscribe jason chaffetz stump american fork utah image courtesy michael jolley available creative commonsby license apologies keith olbermann doubt worst person world weekfbi director james comey according house democratic aide looks like also know secondworst person well turns comey sent nowinfamous letter announcing fbi looking emails may related hillary clintons email server ranking democrats relevant committees didnt hear comey found via tweet one republican committee chairmen know comey notified republican chairmen democratic ranking members house intelligence judiciary oversight committees agency reviewing emails recently discovered order see contained classified information long letter went oversight committee chairman jason chaffetz set political world ablaze tweet fbi dir informed fbi learned existence emails appear pertinent investigation case reopened jason chaffetz jasoninthehouse october course know case comey actually saying reviewing emails light unrelated casewhich know anthony weiners sexting teenager apparently little things facts didnt matter chaffetz utah republican already vowed initiate raft investigations hillary winsat least two years worth possibly entire terms worth apparently chaffetz thought fbi already work himresulting tweet briefly roiled nation cooler heads realized dud according senior house democratic aide misreading letter may least chaffetz sins aide told shareblue boss democrats didnt even know comeys letter timeand found checked twitter democratic ranking members relevant committees didnt receive comeys letter republican chairmen fact democratic ranking members receive chairman oversight government reform committee jason chaffetz tweeted made public lets see weve got right fbi director tells chaffetz gop committee chairmen major development potentially politically explosive investigation neither chaffetz colleagues courtesy let democratic counterparts know instead according aide made find twitter already talk daily kos comey provided advance notice letter chaffetz republicans giving time turn spin machine may make good theater nothing far even suggests case nothing far suggests comey anything grossly incompetent tonedeaf suggest however chaffetz acting way makes dan burton darrell issa look like models responsibility bipartisanship didnt even decency notify ranking member elijah cummings something explosive doesnt trample basic standards fairness dont know granted likely chaffetz answer sits ridiculously republican district anchored provo orem cook partisan voting index r gave mitt romney punishing percent vote moreover republican house leadership given full support chaffetz planned fishing expedition doesnt mean cant turn hot lights textbook example house become republican control also second worst person world darrell lucus darrell something graduate university north carolina considers journalist old school attempt turn member religious right college succeeded turning religious rights worst nightmarea charismatic christian unapologetic liberal desire stand scared silence increased survived abusive threeyear marriage may know daily kos christian dem nc follow twitter darrelllucus connect facebook click buy darrell mello yello connect'

In [136]:
cv = TfidfVectorizer(max_features = 5000, ngram_range= (1,3))
X = cv.fit_transform(data_train.text).toarray()

In [137]:
title_count = pd.DataFrame(X, columns = cv.get_feature_names())

In [138]:
title_count

,aaron,abandoned,abc,abedin,ability,able,abortion,abroad,absence,absolute,...,youre going,youth,youtube,youve,youve got,zero,zika,zone,zones,zu
0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.000000,0.021599,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.000000,0.054871,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18280,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18281,0.043747,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18282,0.000000,0.0,0.0,0.0,0.000000,0.025408,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18283,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18284,0.000000,0.0,0.0,0.0,0.030859,0.024508,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Multinomial NB Algorithm

In [155]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [154]:
X_test.shape

(5486, 5000)

In [152]:
pd.DataFrame(X_test)

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5481,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5482,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5483,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5484,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [139]:
classifier = MultinomialNB()

In [140]:
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)

In [141]:
print(metrics.classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      3107
           1       0.86      0.89      0.87      2379

    accuracy                           0.89      5486
   macro avg       0.89      0.89      0.89      5486
weighted avg       0.89      0.89      0.89      5486

In [142]:
print(metrics.confusion_matrix(y_test, pred))

[[2758  349]
 [ 261 2118]]

In [143]:
sorted(zip(classifier.coef_[0], feature_names), reverse = True)[:20]

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)

[(-4.05200171342031, 'trump'),
 (-4.325928410803606, 'hillary'),
 (-4.447818228412642, 'clinton'),
 (-4.97106637217719, 'us'),
 (-5.024555057128176, 'election'),
 (-5.11256593445089, 'new'),
 (-5.153387928971145, 'comment'),
 (-5.254129498772676, 'video'),
 (-5.33072194425406, 'war'),
 (-5.3765314802853545, 'fbi'),
 (-5.424540699471715, 'hillary clinton'),
 (-5.552622487328673, 'world'),
 (-5.630080546367677, 'donald'),
 (-5.736187052362225, 'obama'),
 (-5.781996588393519, 'donald trump'),
 (-5.838236306716395, 'emails'),
 (-5.863342227847471, 'russia'),
 (-5.89782840391864, 'trumps'),
 (-5.924496651000802, 'wikileaks'),
 (-6.028856666325044, 'vote')]

In [144]:
sorted(zip(classifier.coef_[0], feature_names))[:20]

[(-10.634026852313136, 'abroad'),
 (-10.634026852313136, 'act new'),
 (-10.634026852313136, 'act new york'),
 (-10.634026852313136, 'actions'),
 (-10.634026852313136, 'advice'),
 (-10.634026852313136, 'agenda breitbart'),
 (-10.634026852313136, 'aleppo new'),
 (-10.634026852313136, 'aleppo new york'),
 (-10.634026852313136, 'ali'),
 (-10.634026852313136, 'amazon'),
 (-10.634026852313136, 'america breitbart'),
 (-10.634026852313136, 'america new york'),
 (-10.634026852313136, 'amp'),
 (-10.634026852313136, 'amy'),
 (-10.634026852313136, 'amy schumer'),
 (-10.634026852313136, 'angel'),
 (-10.634026852313136, 'angela'),
 (-10.634026852313136, 'angela merkel'),
 (-10.634026852313136, 'angeles'),
 (-10.634026852313136, 'appearance')]

### Now Applying Word2Vec - Homework